version: '3.1'

services:

  db:
    image: postgres
    container_name: desafio_database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSGRES_DB: desafio_db
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  api:
    container_name: desafio_api
    network_mode: "host"
    build: .
    depends_on:
      - desafio_database
